version: '3.8'
services:
  database:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres_database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres